services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "8085:8084"
    networks:
      - app-network
    environment:
      - API_URL=http://server:8091

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
      args:
        - VOSK_MODEL_SIZE=${VOSK_MODEL_SIZE:-small}
        - TTS_MODEL=${TTS_MODEL:-vits-melo-tts-zh_en}
      # 添加构建缓存设置
      cache_from:
        - eclipse-temurin:21-jre
    ports:
      - "8091:8091"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp1i047rt28fajm69.mysql.rds.aliyuncs.com/xiaozhi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mcgo
      - SPRING_DATASOURCE_PASSWORD=ukj5eWLVVp79MqK
    volumes:
      - maven_repo:/root/.m2/repository  # 持久化Maven仓库
    restart: on-failure  # 添加重启策略，如果启动失败会自动重试

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  maven_repo:  # 持久化 Maven 仓库
